#!/bin/bash

# Path to your text file
file=~/dotfiles/dmenu-data/emails.txt

# Exit if file not found
if [ ! -f "$file" ]; then
    notify-send "Error" "File $file not found"
    exit 1
fi

# Get first column for rofi
entries=$(awk -F';' '{print $1}' "$file")

# Show rofi menu and capture selection
selection=$(echo "$entries" | rofi -dmenu -i -p "Select email: " -matching fuzzy)

# If a selection was made, copy corresponding second column to clipboard
if [ -n "$selection" ]; then
    code=$(awk -F';' -v sel="$selection" '$1==sel {print $2}' "$file")
    if [ -n "$code" ]; then
        if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
            echo -n "$code" | wl-copy
        else
            echo -n "$code" | xclip -selection clipboard
        fi
        notify-send "Success" "email for $selection copied to clipboard"
    else
        notify-send "Error" "No email found for $selection"
        exit 1
    fi
fi
